# This script walks through the process to fix itemize notes in a specific package
# more work could be done to generalise this to other packages and other note types

source("categorise_notes.R")

notes_df |>
  dplyr::filter(note_category == "itemize") |>
  dplyr::group_by(Package) |>
  dplyr::summarise(n = dplyr::n()) |>
  dplyr::arrange(-n)

tmp_dir <- tempdir()
test_pkg_name <- "academictwitteR"

test_pkg <- Rd_NOTE_lb |>
  dplyr::filter(Package == test_pkg_name)

test_pkg_notes <- notes_df |>
  dplyr::filter(Package == test_pkg_name)

if(dir.exists(file.path(tmp_dir, test_pkg_name))) {
  unlink(file.path(tmp_dir, test_pkg_name), force = TRUE, recursive = TRUE)
}

# clone the repo to a temporary directory
repo <- stringr::str_remove(test_pkg$BugReports, "/issues")
git2r::clone(repo, local_path = file.path(tmp_dir, test_pkg_name))

# check the Rd files for roxygen
pth <- file.path(tmp_dir, test_pkg_name, "man")
Rd_files <- list.files(pth, full.names = T)

rd_lines <- readLines(file.path(pth, test_pkg_notes$file_name[1]))

by_roxygen <- stringr::str_detect(rd_lines[1], "% Generated by roxygen2: do not edit by hand")

# Find the R file that generated the Rd file (note there may be more than one)
if(by_roxygen) {
  file <- stringr::str_extract(rd_lines[2], "R/.*\\.R")
}

R_lines <- readLines(file.path(tmp_dir, test_pkg_name, file))

# find the roxygen comment line where itemize is used
itemize_line <- which(stringr::str_detect(R_lines, "\\\\itemize"))

# Fix the lines and write back to the file
R_lines[itemize_line] <- str_replace(R_lines[itemize_line], "\\\\itemize", "\\\\describe")
writeLines(R_lines, file.path(file.path(tmp_dir, test_pkg_name, file)))


# The rest of the notes should then also be fixed here

# Recompile the .Rd files from the fixes
devtools::document(file.path(tmp_dir, test_pkg_name))

# commit the changes to a new branch (locally)
git2r::status(file.path(tmp_dir, test_pkg_name))
git2r::add(file.path(tmp_dir, test_pkg_name), file)
commit_1 <- git2r::commit(file.path(tmp_dir, test_pkg_name), "Test commit")
git2r::branch_create(commit_1, name = "fix_itemize")
git2r::status(file.path(tmp_dir, test_pkg_name))
# Then push the changes to a new branch on GitHub (not done here yet)
