# This script walks through the process to fix itemize notes in a specific package
# more work could be done to generalise this to other packages and other note types

# NOTE: ultimately, we want a function, `fix_itemize(path)` that
# takes a path to a local folder containing the package source and
# applies the fix.
# This function should work for all occurences of the NOTE in the package
# Do not need to worry about package name or url - that is being handled separately
# by other functions (this repo is going to be made into a package)

library(git2r)

source("categorise_notes.R")
source("uses_roxygen.R")

notes_df %>%
  filter(note_category == "itemize") %>%
  group_by(Package) %>%
  summarise(n = n()) %>%
  arrange(-n)

pkgs_itemize_note <- notes_df %>%
  filter(note_category == "itemize") |>
  dplyr::pull(Package) |>
  unique()

# Which packages with itemize NOTES use roxygen2
pkg_note_roxygen <- sapply(pkgs_itemize_note, pkg_uses_roxygen_cran)
table(pkg_note_roxygen)
# Will need to handle the roxygen2 and manual Rd files separately
# For manual Rd files, we can use `line_numbers` in notes_df
# and edit the Rd files directly
# will still need to take care with line numbers as they reference `\item`
# rather than `\itemize` and some line_numbers are multiline (eg 34-35)
# For roxygen2 files, a number more sophisticated approach required
# since line_numbers in .Rd don't match line numbers in associated .R file(s)
# Maybe can use `parse_*` functions from roxygen2?
pkg_note_uses_roxygen <- names(pkg_note_roxygen)[pkg_note_roxygen]
pkg_note_no_roxygen <- names(pkg_note_roxygen)[!pkg_note_roxygen]

# Experiment with a test package that uses roxygen2
# Here using lcsm as it has many NOTES across multiple files
tmp_dir <- tempdir()
test_pkg_name <- "gamlss.dist" # most revdeps of affected packages

test_pkg <- Rd_NOTE_lb %>%
  filter(Package == test_pkg_name)

test_pkg_notes <- notes_df %>%
  filter(Package == test_pkg_name)

if (dir.exists(file.path(tmp_dir, test_pkg_name))) {
  unlink(file.path(tmp_dir, test_pkg_name), force = TRUE, recursive = TRUE)
}

# clone the repo to a temporary directory
repo <- str_remove(test_pkg$BugReports, "/issues")
git2r::clone(repo, local_path = file.path(tmp_dir, test_pkg_name))

# NOTE: this only pulls out the first affected file.
# Script should be adapted to fix all files where this occurs.
# Get all files
Rd_files_with_notes <- unique(test_pkg_notes$file_name)

# TODO: a function that works on one file, then apply it
# Adapt the code below
pth <- file.path(tmp_dir, test_pkg_name, "man", Rd_files_with_notes[1])
rd_lines <- readLines(file.path(pth))

# We are working here with a package we know uses roxygen2,
# but check individual Rd file for belts-and-braces approach
by_roxygen <- str_detect(
  rd_lines[1],
  "% Generated by roxygen2: do not edit by hand"
)

# Find the R file that generated the Rd file (note there may be more than one)
if (by_roxygen) {
  file <- str_extract(rd_lines[2], "R/.*\\.R")
}
#TODO: need to fix Rd directly if `by_roxygen` is `FALSE`

if (by_roxygen) {
  R_lines <- readLines(file.path(tmp_dir, test_pkg_name, file))
}


# find the roxygen comment line where itemize is used
# NOTE: what if there is more than one itemize, but not all of them are a problem?
# NEED TO CHECK LINE NUMBERS IN NOTE - but these line numbers are for the Rd file,
# not the associated R script
# THIS IS A HARD PROBLEM!
itemize_line <- which(str_detect(R_lines, "\\\\itemize"))

## DON'T DO THIS!!!
## Too blunt - could be changing genuine itemize lists
## Need to find a way to link back to the NOTE/lines in the Rd file
# Fix the lines and write back to the file
# R_lines[itemize_line] <- str_replace(
#   R_lines[itemize_line],
#   "\\\\itemize",
#   "\\\\describe"
# )
# writeLines(R_lines, file.path(file.path(tmp_dir, test_pkg_name, file)))

# Recompile the .Rd files from the fixes
# devtools::document(file.path(tmp_dir, test_pkg_name))

# TODO: check the newly generated Rd with tools::checkRd

# commit the changes to a new branch (locally)
# Don't do the git part here: this is being separated out into a separate function
# git2r::status(file.path(tmp_dir, test_pkg_name))
# git2r::add(file.path(tmp_dir, test_pkg_name), file)
# commit_1 <- git2r::commit(file.path(tmp_dir, test_pkg_name), "Test commit")
# git2r::branch_create(commit_1, name = "fix_itemize")
# git2r::status(file.path(tmp_dir, test_pkg_name))
# Then push the changes to a new branch on GitHub (not done here yet)
